### ISSUE TITLE
Unable to read localhost.localdomain

### ISSUE THREAD

**Issue by dmccue** [eucalyptus/calyptos#100]
Unable to read: localhost.localdomain
Traceback (most recent call last):
  File "/usr/bin/calyptos", line 5, in <module>
    pkg_resources.run_script('calyptos==d74ce30', 'calyptos')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/calyptos-d74ce30-py2.7.egg/EGG-INFO/scripts/calyptos", line 285, in <module>

  File "/usr/lib/python2.7/site-packages/calyptos-d74ce30-py2.7.egg/EGG-INFO/scripts/calyptos", line 106, in prepare

  File "/usr/lib/python2.7/site-packages/calyptos-d74ce30-py2.7.egg/EGG-INFO/scripts/calyptos", line 85, in run_driver

  File "build/bdist.linux-x86_64/egg/calyptos/plugins/deployer/chef.py", line 103, in prepare
  File "build/bdist.linux-x86_64/egg/calyptos/chefmanager.py", line 166, in clear_run_list
  File "build/bdist.linux-x86_64/egg/calyptos/chefmanager.py", line 104, in load_local_node_info
  File "build/bdist.linux-x86_64/egg/calyptos/chefmanager.py", line 114, in read_node_hash
ValueError: No JSON object could be decoded

**Comment by shaon** [comment]
@dmccue are you running this from a node that is also part of your eucalyptus deployment? My guess would be it failed to create the node json file. Can you please provide the steps that you followed before hitting this issue?
