### ISSUE TITLE
AssertationError: invalid request network-interfaces.sh (404 error)

### ISSUE THREAD

**Issue by dmccue** [eucalyptus/calyptos#19]
The default environment.yml points to init-script-url at http://git.qa1.eucalyptus-systems.com/qa-repos/eucalele/raw/master/scripts/network-interfaces.sh which returns a 404 error

command:

``` bash
calyptos -e environment.yml validate
```

environment.yml:

``` yaml
[root@odc-f-09 etc]# cat environment.yml 

---
name: scale-system
description: 4.1 EDGE Testing
default_attributes:
  eucalyptus:
    topology:
      clc-1: 10.104.10.51 
      walrus: 10.104.10.44
      user-facing:
      - 10.104.10.51
      clusters:
        one:
          cc-1: 10.104.10.70
          sc-1: 10.104.10.67
          storage-backend: das
          das-device: vg01
          nodes: 10.104.10.73 10.104.10.78 10.104.10.59
    nc:
      max-cores: 128
      cache-size: 11000
      work-size: 160000
    network:
      mode: EDGE
      config-json:
        InstanceDnsServers:
        - 10.113.10.1
        PublicIps:
        - 10.113.150.1-10.113.150.254
        Clusters:
        - Name: one
          Subnet:
            Subnet: 10.104.10.59
            Netmask: 255.255.0.0
            Name: 10.104.0.0
            Gateway: 10.104.0.1
      public-interface: br0
      private-interface: br0
      bridge-interface: br0
      bridged-nic: em1
    init-script-url: http://git.qa1.eucalyptus-systems.com/qa-repos/eucalele/raw/master/scripts/network-interfaces.sh
    eucalyptus-repo: http://packages.release.eucalyptus-systems.com/yum/tags/eucalyptus-devel/centos/6/x86_64/
    euca2ools-repo: http://packages.release.eucalyptus-systems.com/yum/tags/euca2ools-devel/centos/6/x86_64/
    yum-options: "--nogpg"
```

output:

``` python
Traceback (most recent call last):
  File "/usr/bin/calyptos", line 5, in <module>
    pkg_resources.run_script('calyptos==4575d14', 'calyptos')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/calyptos-4575d14-py2.6.egg/EGG-INFO/scripts/calyptos", line 172, in <module>
    cli(obj={})
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.6/site-packages/click-4.0-py2.6.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/calyptos-4575d14-py2.6.egg/EGG-INFO/scripts/calyptos", line 90, in validate
    results = mgr.map_method('validate')
  File "/usr/lib/python2.6/site-packages/stevedore/extension.py", line 243, in map_method
    method_name, *args, **kwds)
  File "/usr/lib/python2.6/site-packages/stevedore/extension.py", line 216, in map
    self._invoke_one_plugin(response.append, func, e, args, kwds)
  File "/usr/lib/python2.6/site-packages/stevedore/extension.py", line 247, in _invoke_one_plugin
    response_callback(func(e, *args, **kwds))
  File "/usr/lib/python2.6/site-packages/stevedore/extension.py", line 221, in _call_extension_method
    return getattr(extension.obj, method_name)(*args, **kwds)
  File "/usr/lib/python2.6/site-packages/calyptos-4575d14-py2.6.egg/calyptos/plugins/validator/repos.py", line 22, in validate
    raise AssertionError("INVALID REQUEST: " + str(url) + "  " + str(e.code))
AssertionError: INVALID REQUEST: http://git.qa1.eucalyptus-systems.com/qa-repos/eucalele/raw/master/scripts/network-interfaces.sh  404
```

**Comment by dmccue** [comment]
Now works, thanks!
