### ISSUE TITLE
'calyptos validate' failing in rolebuilder.py

### ISSUE THREAD

**Issue by dmccue** [eucalyptus/calyptos#99]
calyptos version: 5f09e6e
# calyptos validate -e environment.yml -p ''

Traceback (most recent call last):
  File "/usr/bin/calyptos", line 5, in <module>
    pkg_resources.run_script('calyptos==5f09e6e', 'calyptos')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/calyptos-5f09e6e-py2.7.egg/EGG-INFO/scripts/calyptos", line 289, in <module>

  File "/usr/lib/python2.7/site-packages/calyptos-5f09e6e-py2.7.egg/EGG-INFO/scripts/calyptos", line 93, in validate

  File "build/bdist.linux-x86_64/egg/calyptos/rolebuilder.py", line 30, in **init**
  File "build/bdist.linux-x86_64/egg/calyptos/rolebuilder.py", line 213, in get_roles
TypeError: unhashable type: 'list'

**Comment by nephomaniac** [comment]
Thanks @dmccue, 
Is it possible the cassandra host is another list?
Could you post the yaml used for this run, or possibly just the cassandras portion? 
Here's a sample portion of yaml from a recent test I ran. 

midokura:
    cassandras:
    - 10.111.X.X
    initial-tenant: euca_tenant_1
    midolman-host-mapping:
      c-xx.qa1.eucalyptus-systems.com: 10.111.X.X
      c-xy.qa1.eucalyptus-systems.com: 10.111.X.Y
      c-xz.qa1.eucalyptus-systems.com: 10.111.X.Z

This could use a better errror, and type checking here when parsing the yaml it seems. 
Thanks -M

**Comment by dmccue** [comment]
&MIDO_REPO_URL
  http://xxxxx:xxxxx@yum.midokura.com/repo/v1.9/stable/RHEL/6/
&MIDO_API_ADDRESS
  http://10.143.58.180:8080/midonet-api
&MIDO_ZOOKEEPERS
    - *VAR_CLC_IP
    - *VAR_CC_IP_1
    - *VAR_CC_IP_2
&MIDO_CASSANDRAS
    - *VAR_CLC_IP
    - *VAR_CC_IP_1
    - *VAR_CC_IP_2
&MIDO_HOST_MAPPINGS
      dalxxxxxx: x.x.x.x
      dalxxxxxx: x.x.x.x
      dalxxxxxx: x.x.x.x
      dalxxxxxx: x.x.x.x
      dalxxxxxx: x.x.x.x
      dalxxxxxx: x.x.x.x
      dalxxxxxx: x.x.x.x

  midokura:
    repo-url: *MIDO_REPO_URL
    yum-options: --nogpg
    initial-tenant: euca_tenant_1
    midonet-api-url: *MIDO_API_ADDRESS
    cassandras:
      *MIDO_CASSANDRAS
    zookeepers:
      *MIDO_ZOOKEEPERS
    midolman-host-mapping:
      *MIDO_HOST_MAPPINGS
